from bert_score import score


### High-Faithfulness Answers ###

#this is answer
generated_text = ["The family planning services funded through the HHSC Family Planning Program include: Health history and physical examinations, Counseling and education, Laboratory testing, Provision of a contraceptive method, Pregnancy tests, Sexually transmitted infection screenings and treatment, Referrals for additional services as needed, Immunizations, Breast and cervical cancer screening and diagnostic services, Prenatal services, Other services subject to available funding",
                  "The sources that TPR (Third Party Resources) includes for payments for Texas Medicaid are: Other health insurance including assignable indemnity contracts  Health maintenance organization (HMO) Public health programs available to clients with Medicaid such as Medicare and Tricare  Profit and nonprofit health plans",
                  "If a claim was initially sent to the adoption agency before being sent to Texas Medicaid Healthcare Partnership (TMHP), TMHP must receive the claim within 95 days of the date of disposition from the adoption agency. This disposition could be a denial, payment, request for refund, or recoupment. Therefore, the claim should be sent to TMHP within this 95-day period to be considered for payment."]

#this is ground truth
original_text = ["The family planning services needed are Health history and physical Counseling and education Laboratory testing, Provision of a contraceptive method, Pregnancy tests, Sexually transmitted infection screenings and treatment, Referrals for additional services, as needed, Immunizations,Breast and cervical cancer screening and diagnostic services,Prenatal services, and Other services subject to available funding",
                 "TPR includes payments from any of the following sources: Other health insurance including assignable indemnity contract, Health maintenance organization (HMO), Public health programs available to clients with Medicaid such as Medicare and Tricare, Profit and nonprofit health plan, Employment-related health insurance, Self-insured plans, Casualty coverage resulting from an accidental injury such as automobile or property insurance, (including no-fault insurance); No-fault automobile insurance such as personal injury protection, (PIP) and automobile medical insurance, Liability insurance, Life insurance policies, trust funds, cancer policies, or other supplemental policies, Workersâ€™ Compensation, Medical support from absent parents, Court judgments or settlements from a liability insurer, First party probate-estate recoveries, Other federal programs unless excluded by statute, Other liable third parties",
                 "TMHP must receive the claim within 95 days of the date of disposition from the adoption agency denial, payment, requests for refund or recoupment, to be considered for payment."]

#calculate the bert score
P_1, R_1, F1_1 = score(generated_text, original_text, lang = "en", verbose = True)

print(f"Precision of High-Faith: {P_1.mean()}")
print(f"Recall of High-Faith: {R_1.mean()}")
print(f"F1 of High-Faith: {F1_1.mean()}")

### Low-Faithfulness Answers ###

#this is answer
generated_text = ["To handle a planning examination for an additional E/M (Evaluation and Management) office visit that goes beyond the required components for a standard office visit, a client can take the following steps: Understand the Requirements: First, the client should understand what the standard components of an E/M office visit are, and what additional components are being considered for the examination. This involves knowing the criteria for different levels of E/M services as defined by the relevant healthcare guidelines (such as those from the CMS or AMA). Documentation: Ensure that all additional examinations or services provided are thoroughly documented. The documentation should clearly state the medical necessity of these additional components. This includes detailing how the patientâ€™s condition warrants these extra steps and how they are expected to contribute to better diagnostic or treatment outcomes. Communication with Healthcare Provider: The client should discuss with their healthcare provider why these additional components are necessary and how they will benefit the patient's health. Understanding the rationale behind the additional components can also help in explaining the situation to the insurance provider if needed.  Insurance Verification: Before proceeding with the additional components of the E/M visit, check with the insurance provider to verify coverage. This can prevent unexpected expenses and ensure that both the healthcare provider and the patient are clear about what will be covered. Consent: Itâ€™s important that the client gives informed consent, acknowledging that they understand what the additional examination entails, the reasons for it, and any associated costs if not covered by insurance.  Follow-Up: After the additional E/M office visit, the client should follow up to receive any results or further instructions. This ensures continuity of care and maximizes the effectiveness of the additional examination components.  By taking these steps, a client can effectively manage and utilize an additional E/M office visit to ensure comprehensive medical evaluation and care.",
                  "The optimal process for submitting Third Party Resources (TPR) claims to Texas Medicaid involves several key steps:Identify TPR Sources: Determine if the client has coverage from other health insurance, HMOs, public health programs like Medicare and Tricare, or any profit or nonprofit health plan.Submit Claim to TPR: Initially, submit the claim to the identified TPR source(s) to determine their liability and the amount they will pay.Assess TPR Payment: After receiving payment from the TPR, assess whether the amount covers the Medicaid-allowable amount for the services provided.Submit Claim to TMHP: If the TPR payment is less than the Medicaid-allowable amount, submit a claim to the Texas Medicaid & Healthcare Partnership (TMHP) for the additional allowable amount.Follow Filing Deadlines: Ensure that claims are submitted within the filing deadlines as specified in Subsection 6.1.4, â€œClaims Filing Deadlinesâ€ in â€œSection 6: Claims Filingâ€ of the TMHP manual.Handle Denied Claims: If claims are denied or services are not covered by Medicaid, consider submitting these claims to non-TPR sources.Refund Erroneous Payments: If a non-TPR source erroneously makes a payment for a service also covered by Medicaid, refund the payment to the non-TPR source.Contact Provider Relations for Assistance: If there are any uncertainties or specific situations not covered by standard procedures, contact a provider relations representative for guidance.",
                  "Clients with disabilities can receive eligibility for Medicaid by meeting specific criteria set by their state. Generally, they must demonstrate that they have a disability as defined by the Social Security Administration (SSA). This often involves providing medical evidence of their disability. Additionally, they must meet certain income and asset requirements, which vary by state. Some states may have expanded Medicaid eligibility under the Affordable Care Act, which could also affect the criteria. It's advisable for individuals to contact their state's Medicaid office to get detailed information about the eligibility requirements and the application process."]

#this is ground truth
original_text = ["An annual family planning examination (billed with modifier FP) will not be reimbursed when submitted with the same date of service as an additional E/M visit. If another condition requiring an E/M office visit beyond the required components for an office visit, family planning visit, or surgical procedure is discovered, the provider may submit a claim for the additional visit using Modifier 25 to indicate that the clientâ€™s condition required a significant, separately identifiable E/M service. Documentation supporting the provision of a significant, separately identifiable E/M service must be maintained in the clientâ€™s medical record and made available to Texas Medicaid upon request.",
                 "These informational claims must be submitted to the THMP within 95 days as a Submission Form with the Name of TPR and the client's health reason whether its for any dental plan, birth control, fatal accidental injury in order for clients to seek proper medical coverage from Texas Medicaid and refunds are considered when the client makes a false payment in which they will need to reissue the claim back to their TPR for consultation.",
                 "These individuals can recieve medical coverage through a monthly premium as its mainly used for impoverished people with earning less than 250% and have infants that weight less than 1200lbs. This can also apply to minor citizens as well where they seek Medical coverage from the MBIC Program with family income less than 300%. The only catch is that they must keep up-to-date their appoinments to mantain eligibility staturs and past a month of not meeting finanacial and disability criteria can de-register the client from the Medicare Program."]
#calculate the bert score
P_2, R_2, F1_2 = score(generated_text, original_text, lang = "en", verbose = True)

print(f"Precision of Low-Faith: {P_2.mean()}")
print(f"Recall of Low-Faith: {R_2.mean()}")
print(f"F1 of Low-Faith: {F1_2.mean()}")


### Combination of Faithfulness Answers ###

#this is answer
generated_text = ["An emergency behavioral health condition is any condition that, according to a reasonable person without specialized medical knowledge, requires immediate medical intervention. This urgency is due to the potential immediate danger the condition poses to the individual or others, or because it prevents the individual from controlling, understanding, or being aware of the consequences of their actions.",
                  "The requirements for an ambulance provider to bill for ET3 services, based on the provided context, include: Transporting a client to an alternative destination other than an emergency department, such as an urgent care clinic, mental health center, or Federally Qualified Health Center (FQHC), based on the evaluation of the client's condition. Initiating and facilitating appropriate treatment in place (TIP) at the scene of the emergency.  Initiating and facilitating appropriate TIP through telemedicine or telehealth, as defined in the Telecommunication Services Handbook (Vol. 2, Provider Handbooks).  These options allow ambulance providers to address the client's healthcare needs more flexibly and appropriately after a 9-1-1 call or other emergency calls, potentially reducing unnecessary visits to emergency departments.",
                  "If a claim was initially sent to the adoption agency before being sent to Texas Medicaid Healthcare Partnership (TMHP), TMHP must receive the claim within 95 days of the date of disposition from the adoption agency. This disposition could be a denial, payment, request for refund, or recoupment. Therefore, the claim should be sent to TMHP within this 95-day period to be considered for payment.",
                  "The Third Party Liability (TPL) program supports the provision of payments for managed care to Texas Medicaid clients by recovering payments from third parties that are legally responsible for paying medical claims. This process helps reduce Medicaid costs by shifting the financial responsibility for these claims to the appropriate third party payers, rather than having them solely funded by Medicaid. This ensures that Medicaid can allocate its resources more efficiently and sustainably, supporting the overall management and provision of care to its clients.",
                  "Clients with disabilities can receive eligibility for Medicaid by meeting specific criteria set by their state. Generally, they must demonstrate that they have a disability as defined by the Social Security Administration (SSA). This often involves providing medical evidence of their disability. Additionally, they must meet certain income and asset requirements, which vary by state. Some states may have expanded Medicaid eligibility under the Affordable Care Act, which could also affect the criteria. It's advisable for individuals to contact their state's Medicaid office to get detailed information about the eligibility requirements and the application process."]

#this is ground truth
original_text = ["An emergency behavioral health condition is defined as any condition that, in the opinion of a prudent layperson with an average knowledge of health and medicine, requires immediate intervention or medical attention regardless of the nature, without which the client would present an immediate danger to himself, or herself or others, or that renders the client incapable of controlling, knowing, or understanding the consequences of his or her actions.",
                 "The requirements for an ambulance provider to bill for ET3 services, based on the provided context, include: Transporting a client to an alternative destination other than an emergency department, such as an urgent care clinic, mental health center, or Federally Qualified Health Center (FQHC), based on the evaluation of the client's condition. Initiating and facilitating appropriate treatment in place (TIP) at the scene of the emergency.  Initiating and facilitating appropriate TIP through telemedicine or telehealth, as defined in the Telecommunication Services Handbook (Vol. 2, Provider Handbooks).  These options allow ambulance providers to address the client's healthcare needs more flexibly and appropriately after a 9-1-1 call or other emergency calls, potentially reducing unnecessary visits to emergency departments.",
                 "TMHP must receive the claim within 95 days of the date of disposition from the adoption agency denial, payment, requests for refund or recoupment, to be considered for payment.",
                 "They can limit the amount additional costs that Texas Medicaid offers to clients when relying on a TPR to provide claims when recovering any health insurance and commerical MCOs.",
                 "These individuals can recieve medical coverage through a monthly premium as its mainly used for impoverished people with earning less than 250% and have infants that weight less than 1200lbs. This can also apply to minor citizens as well where they seek Medical coverage from the MBIC Program with family income less than 300%. The only catch is that they must keep up-to-date their appoinments to mantain eligibility staturs and past a month of not meeting finanacial and disability criteria can de-register the client from the Medicare Program."]
#calculate the bert score
P_3, R_3, F1_3 = score(generated_text, original_text, lang = "en", verbose = True)

print(f"Precision of Combination of Different Faiths: {P_3.mean()}")
print(f"Recall of Combination of Different Faiths: {R_3.mean()}")
print(f"F1 of Combination of Different Faiths: {F1_3.mean()}")